INSERT INTO country (country_name, language)
VALUES
  ('Afghanistan', 'Dari Persian'),
  ('Albania', 'Albanian'),
  ('Algeria', 'Arabic'),
  ('Andorra', 'Catalán'),
  ('Angola', 'Portuguese'),
  ('Antigua and Barbuda', 'English'),
  ('Argentina', 'Spanish'),
  ('Armenia', 'Armenian'),
  ('Australia', 'English'),
  ('Austria', 'German'),
  ('Azerbaijan', 'Azerbaijani Turkic'),
  ('Bahamas', 'English'),
  ('Bahrain', 'Arabic'),
  ('Bangladesh', 'Bangla'),
  ('Barbados', 'English'),
  ('Belarus', 'Belorussian'),
  ('Belgium', 'Dutch'),
  ('Belize', 'English'),
  ('Benin', 'French'),
  ('Bhutan', 'Dzongkha'),
  ('Bolivia', 'Spanish'),
  ('Bosnia and Herzegovina', 'Bosnian'),
  ('Botswana', 'English'),
  ('Brazil', 'Portuguese'),
  ('Brunei', 'Malay'),
  ('Bulgaria', 'Bulgarian'),
  ('Burkina Faso', 'French'),
  ('Burundi', 'Kirundi and French'),
  ('Cambodia', 'Khmer'),
  ('Cameroon', 'French'),
  ('Canada', 'English'),
  ('Cape Verde', 'Portuguese'),
  ('Central African Republic', 'French'),
  ('Chad', 'French'),
  ('Chile', 'Spanish'),
  ('China', 'Standard Chinese'),
  ('Colombia', 'Spanish'),
  ('Comoros', 'Arabic and French'),
  ('Congo', 'French'),
  ('Costa Rica', 'Spanish'),
  ('Cote d Ivoire', 'French'),
  ('Croatia', 'Croatian'),
  ('Cuba', 'Spanish'),
  ('Cyprus', 'Greek'),
  ('Czech Republic', 'Czech'),
  ('Denmark', 'Danish'),
  ('Djibouti', 'French AND Arabic'),
  ('Dominica', 'English'),
  ('Dominican Republic', 'Spanish'),
  ('East Timor', 'Tetum'),
  ('Ecuador', 'Spanish'),
  ('Egypt', 'Arabic'),
  ('El Salvador', 'Spanish'),
  ('Equatorial Guinea', 'Spanish'),
  ('Eritrea', 'Afar'),
  ('Estonia', 'Estonian'),
  ('Ethiopia', 'Amharic'),
  ('Fiji', 'English'),
  ('Finland', 'Finnish'),
  ('France', 'French'),
  ('Gabon', 'French'),
  ('Gambia', 'English'),
  ('Georgia', 'Georgian'),
  ('Germany', 'German'),
  ('Ghana', 'English'),
  ('Greece', 'Greek'),
  ('Grenada', 'English'),
  ('Guatemala', 'Spanish'),
  ('Guinea', 'French'),
  ('Guinea-Bissau', 'Portuguese'),
  ('Guyana', 'English'),
  ('Haiti', 'Creole AND French'),
  ('Honduras', 'Spanish'),
  ('Hungary', 'Magyar'),
  ('Iceland', 'Icelandic'),
  ('India', 'Hindi'),
  ('Indonesia', 'Bahasa Indonesia'),
  ('Iran', 'Persian AND Persian dialects'),
  ('Iraq', 'Arabic'),
  ('Ireland', 'English'),
  ('Israel', 'Hebrew'),
  ('Italy', 'Italian'),
  ('Jamaica', 'English'),
  ('Japan', 'Japanese'),
  ('Jordan', 'Arabic'),
  ('Kazakhstan', 'Kazak'),
  ('Kenya', 'English'),
  ('Kiribati', 'English'),
  ('Korea North', 'Korean'),
  ('Korea South', 'Korean'),
  ('Kosovo', 'Albanian'),
  ('Kuwait', 'Arabic'),
  ('Kyrgyzstan', 'Kyrgyz'),
  ('Laos', 'Lao'),
  ('Latvia', 'Latvian'),
  ('Lebanon', 'Arabic'),
  ('Lesotho', 'English'),
  ('Liberia', 'English'),
  ('Libya', 'Arabic'),
  ('Liechtenstein', 'German'),
  ('Lithuania', 'Lithuanian'),
  ('Luxembourg', 'Luxermbourgish'),
  ('Macedonia', 'Macedonian'),
  ('Madagascar', 'Malagasy AND French'),
  ('Malawi', 'Chichewa'),
  ('Malaysia', 'Bahasa Melayu'),
  ('Maldives', 'Maldivian Dhivehi'),
  ('Mali', 'French'),
  ('Malta', 'Maltese AND English'),
  ('Marshall Islands', 'Marshallese'),
  ('Mauritania', 'Hassaniya Arabic'),
  ('Mauritius', 'English LESS THAN '),
  ('Mexico', 'Spanish'),
  ('Micronesia', 'English'),
  ('Moldova', 'Moldovan'),
  ('Monaco', 'French'),
  ('Mongolia', 'Mongolian'),
  ('Montenegro', 'Serbian/Montenegrin'),
  ('Morocco', 'Arabic'),
  ('Mozambique', 'Portuguese'),
  ('Myanmar', 'Burmese'),
  ('Namibia', 'English'),
  ('Nauru', 'Nauruan'),
  ('Nepal', 'Nepali'),
  ('Netherlands', 'Dutch'),
  ('New Zealand', 'English'),
  ('Nicaragua', 'Spanish'),
  ('Niger', 'French'),
  ('Nigeria', 'English'),
  ('Norway', 'Bokmål Norwegian'),
  ('Oman', 'Arabic'),
  ('Pakistan', 'Urdu'),
  ('Palau', 'Palauan'),
  ('Panama', 'Spanish'),
  ('Papua New Guinea', 'Tok Pisin'),
  ('Paraguay', 'Spanish'),
  ('Peru', 'Spanish'),
  ('Philippines', 'Filipino'),
  ('Poland', 'Polish'),
  ('Portugal', 'Portuguese'),
  ('Qatar', 'Arabic'),
  ('Romania', 'Romanian'),
  ('Russia', 'Russian'),
  ('Rwanda', 'Kinyarwanda'),
  ('St.Kitts AND Nevis', 'English'),
  ('St.Lucia', 'English'),
  ('St.Vincent AND the Grenadines', 'English'),
  ('Samoa', 'Samoan'),
  ('San Marino', 'Italian'),
  ('São Tomé AND Príncipe', 'Portuguese'),
  ('Saudi Arabia', 'Arabic'),
  ('Senegal', 'French'),
  ('Serbia', 'Serbian'),
  ('Seychelles', 'Seselwa Creole'),
  ('Sierra Leone', 'English'),
  ('Singapore', 'Mandarin'),
  ('Slovakia', 'Slovak'),
  ('Slovenia', 'Slovenian'),
  ('Solomon Islands', 'English'),
  ('Somalia', 'Somali'),
  ('South Africa', 'IsiZulu'),
  ('South Sudan', 'English'),
  ('Spain', 'Castilian Spanish'),
  ('Sri Lanka', 'Sinhala'),
  ('Sudan', 'Arabic'),
  ('Suriname', 'Dutch'),
  ('Swaziland', 'English'),
  ('Sweden', 'Swedish'),
  ('Switzerland', 'German'),
  ('Syria', 'Arabic'),
  ('Taiwan', 'Chinese'),
  ('Tajikistan', 'Tajik'),
  ('Tanzania', 'Swahili'),
  ('Thailand', 'Thai'),
  ('Togo', 'French'),
  ('Tonga', 'Tongan'),
  ('Trinidad AND Tobago', 'English'),
  ('Tunisia', 'Arabic'),
  ('Turkey', 'Turkish'),
  ('Turkmenistan', 'Turkmen'),
  ('Tuvalu', 'Tuvaluan'),
  ('Uganda', 'English'),
  ('Ukraine', 'Ukrainian'),
  ('United Arab Emirates', 'Arabic'),
  ('United Kingdom', 'English'),
  ('United States', 'English'),
  ('Uruguay', 'Spanish'),
  ('Uzbekistan', 'Uzbek'),
  ('Vanuatu', 'Bislama'),
  ('Vatican City', 'Italian'),
  ('Venezuela', 'Spanish'),
  ('Vietnam', 'Vietnamese'),
  ('Western Sahara', 'Hassaniya Arabic'),
  ('Yemen', 'Arabic'),
  ('Zambia', 'English'),
  ('Zimbabwe', 'English');