INSERT INTO users (user_name, user_group_id, location_id)
VALUES
	('Yuki Stroh', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Shanghai')),
	('Tera Dubreuil', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Sudbury')),
	('Tomasa Atienza', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Belfast')),
	('Jacob Defilippo', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Nagano')),
	('Olympia Petersen', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Minneapolis')),
	('Claud Meagher', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Mandurah')),
	('Myron Gracia', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Teresina')),
	('Danika Dewberry', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Indianapolis')),
	('Wilmer Leblanc', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Tulsa')),
	('Joseph Nicolson', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Qingdao')),
	('Claude Silguero', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Grytviken')),
	('Amee Depuy', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Tucson')),
	('Cecelia Mathieu', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Swansea')),
	('Forest Tillett', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Cambridge')),
	('Fernando Cassel', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Charleston')),
	('Eusebio Lancaster', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Gibraltar')),
	('Flor Brain', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Sault Ste Marie')),
	('Jayson Hadden', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Tokyo')),
	('Erik Liska', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Leicester')),
	('Pauline Fondren', (SELECT id FROM user_group WHERE group_name ='ADMIN'), (SELECT id FROM location WHERE location_name = 'Windsor')),
	('Ida Guinyard', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Adelaide')),
	('Verna Baylor', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Harbin')),
	('Betsy Okafor', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Xian')),
	('Rolf Darrell', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Yamaguchi')),
	('Katelyn Dilday', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Florianópolis')),
	('Vincenza Kardos', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Manaus')),
	('Rasheeda Siller', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Yamoussoukro')),
	('Faith Hakes', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Campinas')),
	('Arica Amundson', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Yarmouth')),
	('Mariel Hasegawa', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Port Hedland')),
	('Shonta Whipkey', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Aberdeen')),
	('Keli Maclean', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Juazeiro do Norte')),
	('Dorsey Simoneau', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Regina')),
	('Earle Beagle', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Perth')),
	('Julieta Mendonca', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Utsunomiya')),
	('Rosalyn Hewett', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Niigata')),
	('Frederica Champagne', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Shanghai')),
	('Al Tatham', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Sudbury')),
	('Dennise Sobers', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Belfast')),
	('Elin Kuhn', (SELECT id FROM user_group WHERE group_name ='MANAGER'), (SELECT id FROM location WHERE location_name = 'Nagano')),
	('Kimberli Tweed', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Minneapolis')),
	('Emil Cinnamon', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Mandurah')),
	('Tandra Bratcher', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Teresina')),
	('Edmundo Boisvert', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Indianapolis')),
	('Rozanne Mcinturff', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Tulsa')),
	('Aurea Opitz', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Qingdao')),
	('Luella Pettengill', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Grytviken')),
	('Brady Tolar', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Tucson')),
	('Ha Berkley', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Swansea')),
	('Trang Mckeighan', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Cambridge')),
	('Terisa Suiter', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Charleston')),
	('Brittani Chait', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Gibraltar')),
	('Chae Foraker', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Sault Ste Marie')),
	('Tari Schieber', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Tokyo')),
	('Maya Rodden', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Leicester')),
	('Josette Tineo', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Windsor')),
	('Idalia Twomey', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Adelaide')),
	('Pamala Cartier', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Harbin')),
	('Lamar Gilyard', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Xian')),
	('Darci Treat', (SELECT id FROM user_group WHERE group_name ='CUSTOMER'), (SELECT id FROM location WHERE location_name = 'Yamaguchi'));